mod common;

use common::TempDir;

use rusqlite::Connection;
use std::fs;

use bgone::cli::parse_ports_file;
use bgone::db;
use bgone::describe;
use bgone::exporter;
use bgone::graph::{
    next_sibling_index, prev_sibling_index, DependencyGraph, NodeId, Provenance, RowKind,
    SectionKind,
};
use bgone::indexer;
use bgone::reader::SystemOptions;
use bgone::ui::{
    next_focus, prev_focus, recenter_offset, tree_op, Focus, RecenterPosition, TreeOp,
};

// ============================================================================
// 1. READER TESTS (Existing Options & make.conf)
// ============================================================================

#[test]
fn test_reader_precedence_and_parsing() {
    let temp = TempDir::new("reader");

    // Setup mock /var/db/ports/www_apache24/options
    let ports_dir = temp.path.join("ports");
    let apache_opts_dir = ports_dir.join("www_apache24");
    fs::create_dir_all(&apache_opts_dir).unwrap();
    fs::write(
        apache_opts_dir.join("options"),
        "# This file is auto-generated by 'make config'.\n# Options for apache24-2.4.58\n\
         _OPTIONS_READ=apache24-2.4.58\n_FILE_COMPLETE_OPTIONS_LIST=DOCS HTTP2\n\
         OPTIONS_FILE_SET+=HTTP2\nOPTIONS_FILE_UNSET+=DOCS\n",
    )
    .unwrap();

    // Setup mock make.conf
    let make_conf = temp.path.join("make.conf");
    fs::write(
        &make_conf,
        "# Global options\nOPTIONS_SET+=GLOBAL_SET\nOPTIONS_UNSET+=GLOBAL_UNSET\n",
    )
    .unwrap();

    let sys_opts = SystemOptions::load(&ports_dir, Some(&make_conf));

    // 1. Per-port overrides
    assert!(sys_opts.get_state("www/apache24", "HTTP2", false));
    assert!(!sys_opts.get_state("www/apache24", "DOCS", true));

    // 2. Global make.conf overrides
    assert!(sys_opts.get_state("dns/bind9", "GLOBAL_SET", false));
    assert!(!sys_opts.get_state("dns/bind9", "GLOBAL_UNSET", true));

    // 3. Fallback to Makefile defaults when no override exists
    assert!(sys_opts.get_state("www/apache24", "UNTOUCHED_OPT", true));
    assert!(!sys_opts.get_state("www/apache24", "UNTOUCHED_OPT", false));
}

/// Files bgone wrote before it emitted `OPTIONS_FILE_SET`/`OPTIONS_FILE_UNSET`
/// still describe the user's picks, so they keep loading.
#[test]
fn test_reader_accepts_legacy_with_without_format() {
    let temp = TempDir::new("reader_legacy");

    let ports_dir = temp.path.join("ports");
    let apache_opts_dir = ports_dir.join("www_apache24");
    fs::create_dir_all(&apache_opts_dir).unwrap();
    fs::write(
        apache_opts_dir.join("options"),
        "# Generated by bgone\n_OPTIONS_READ=apache24\nWITH_HTTP2=true\nWITHOUT_DOCS=true\n",
    )
    .unwrap();

    let sys_opts = SystemOptions::load(&ports_dir, None);

    assert!(sys_opts.get_state("www/apache24", "HTTP2", false));
    assert!(!sys_opts.get_state("www/apache24", "DOCS", true));
}

/// `OPTIONS_SET_FORCE` shares a prefix with `OPTIONS_SET` but is a different
/// variable, and must not be parsed as one.
#[test]
fn test_reader_ignores_prefixed_lookalike_variables() {
    let temp = TempDir::new("reader_lookalike");

    let make_conf = temp.path.join("make.conf");
    fs::write(
        &make_conf,
        "OPTIONS_SET_FORCE+=FORCED\nOPTIONS_SET+=PLAIN\n",
    )
    .unwrap();

    let sys_opts = SystemOptions::load(&temp.path.join("nonexistent"), Some(&make_conf));

    assert!(sys_opts.get_state("www/apache24", "PLAIN", false));
    assert!(!sys_opts.get_state("www/apache24", "FORCED", false));
}

// ============================================================================
// 2. EXPORTER TESTS (Output File Validation & Dry-Run)
// ============================================================================

#[test]
fn test_exporter_writes_valid_options_files() {
    let temp = TempDir::new("exporter_write");
    let options_dir = temp.path.join("ports");
    let make_conf_path = temp.path.join("make.conf");

    // Set up database and graph
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('www/apache24', 'HTTP2', 1, 'Enable HTTP2', 'DEFINE', ''),
                ('www/apache24', 'DOCS', 0, 'Build Docs', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/apache24".to_string()], &sys_opts, false)
            .unwrap();

    // Export options
    let stats =
        exporter::export_options(&graph, &options_dir, false, Some(&make_conf_path)).unwrap();

    assert_eq!(stats.files_written, 1);
    assert_eq!(stats.options_saved, 2);

    // Validate generated /var/db/ports/www_apache24/options file content
    let exported_file = options_dir.join("www_apache24").join("options");
    assert!(exported_file.exists());

    let content = fs::read_to_string(&exported_file).unwrap();
    assert!(content.contains("# This file is auto-generated by bgone."));
    assert!(content.contains("_OPTIONS_READ=apache-2.4.58"));
    // Every defined option must be listed, or config-conditional re-prompts
    assert!(content.contains("_FILE_COMPLETE_OPTIONS_LIST=DOCS HTTP2"));
    assert!(content.contains("OPTIONS_FILE_SET+=HTTP2"));
    assert!(content.contains("OPTIONS_FILE_UNSET+=DOCS"));

    // Validate generated make.conf file content
    assert!(make_conf_path.exists());
    let make_content = fs::read_to_string(&make_conf_path).unwrap();
    assert!(make_content.contains("OPTIONS_SET+=HTTP2"));
    assert!(make_content.contains("OPTIONS_UNSET+=DOCS"));
}

/// The indexer only reads PORTVERSION, so ports setting DISTVERSION land in the
/// cache with a placeholder or empty version. Neither may reach the file as a
/// dangling `name-`.
#[test]
fn test_exporter_omits_unknown_versions_from_the_pkgname_header() {
    let temp = TempDir::new("exporter_versions");
    let options_dir = temp.path.join("ports");

    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES
            ('www/nginx', 'nginx', '', 'Web Server'),
            ('www/brotli', 'brotli', 'latest', 'Compression'),
            ('www/known', 'known', '1.2.3', 'Known Version')",
        [],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('www/nginx', 'HTTPV3', 0, '', 'DEFINE', ''),
                ('www/brotli', 'STATIC', 0, '', 'DEFINE', ''),
                ('www/known', 'DOCS', 0, '', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec![
        "www/nginx".to_string(),
        "www/brotli".to_string(),
        "www/known".to_string(),
    ];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    exporter::export_options(&graph, &options_dir, false, None).unwrap();

    let read = |port: &str| fs::read_to_string(options_dir.join(port).join("options")).unwrap();

    assert!(read("www_nginx").contains("_OPTIONS_READ=nginx\n"));
    assert!(read("www_brotli").contains("_OPTIONS_READ=brotli\n"));
    assert!(read("www_known").contains("_OPTIONS_READ=known-1.2.3\n"));
}

/// What the exporter writes must be what the reader reads back, otherwise a
/// second run silently discards the previous session's choices.
#[test]
fn test_exported_options_round_trip_through_the_reader() {
    let temp = TempDir::new("exporter_roundtrip");
    let options_dir = temp.path.join("ports");

    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('www/apache24', 'HTTP2', 1, 'Enable HTTP2', 'DEFINE', ''),
                ('www/apache24', 'DOCS', 0, 'Build Docs', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/apache24".to_string()], &sys_opts, false)
            .unwrap();
    exporter::export_options(&graph, &options_dir, false, None).unwrap();

    // Defaults inverted, so anything not genuinely read back flips state
    let reloaded = SystemOptions::load(&options_dir, None);
    assert!(reloaded.get_state("www/apache24", "HTTP2", false));
    assert!(!reloaded.get_state("www/apache24", "DOCS", true));

    let regraph =
        DependencyGraph::load_from_db(&conn, &["www/apache24".to_string()], &reloaded, false)
            .unwrap();
    assert!(!regraph.is_dirty());
}

#[test]
fn test_exporter_dry_run_creates_no_files() {
    let temp = TempDir::new("exporter_dryrun");
    let options_dir = temp.path.join("ports");

    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('sysutils/tmux', 'tmux', '3.3', 'Terminal Multiplexer')",
        [],
    ).unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('sysutils/tmux', 'UTF8BIDI', 1, 'Support UTF8 BIDI', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["sysutils/tmux".to_string()], &sys_opts, false)
            .unwrap();

    // Run export in dry-run mode
    let stats =
        exporter::export_options(&graph, &options_dir, true, None::<&std::path::PathBuf>).unwrap();

    assert_eq!(stats.files_written, 1);
    assert!(
        !options_dir.exists(),
        "Dry run must NOT create files on disk!"
    );
}

// ============================================================================
// 3. INDEXER & DB TESTS (Parallel Processing & Parser)
// ============================================================================

#[test]
fn test_indexer_parses_ports_dir_into_sqlite() {
    let temp = TempDir::new("indexer");
    let ports_root = temp.path.join("ports");

    // Construct mock ports directory tree
    let nginx_dir = ports_root.join("www").join("nginx");
    fs::create_dir_all(&nginx_dir).unwrap();

    let makefile_content = r#"
PORTNAME=   nginx
PORTVERSION=1.24.0
COMMENT=    Robust HTTP and reverse proxy server

OPTIONS_DEFINE=   HTTP2 SSL DEBUG
OPTIONS_SINGLE=   GZIP
OPTIONS_SINGLE_GZIP= GZIP_DEF GZIP_ALT
OPTIONS_DEFAULT=  HTTP2 GZIP_DEF

HTTP2_DESC=       Enable HTTP2 protocol support
SSL_DESC=         Enable SSL protocol support

HTTP2_RUN_DEPENDS= www/nghttp2

LIB_DEPENDS=  libpcre2-8.so:devel/pcre2
BUILD_DEPENDS= pkgconf:devel/pkgconf
RUN_DEPENDS=  ${LOCALBASE}/bin/nowhere:devel/nonexistent
"#;
    fs::write(nginx_dir.join("Makefile"), makefile_content).unwrap();

    // The ports the Makefile above depends on. Only dependencies pointing at
    // ports that actually exist survive indexing.
    for (category, port) in [("www", "nghttp2"), ("devel", "pcre2"), ("devel", "pkgconf")] {
        let dir = ports_root.join(category).join(port);
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("Makefile"),
            format!("PORTNAME=   {}\nPORTVERSION=1.0\n", port),
        )
        .unwrap();
    }

    let mut conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let stats = indexer::index_ports_dir(&mut conn, &ports_root).unwrap();

    assert_eq!(stats.ports_indexed, 4);
    assert_eq!(stats.options_indexed, 5); // HTTP2, SSL, DEBUG, GZIP_DEF, GZIP_ALT
    assert_eq!(stats.option_deps_indexed, 1); // HTTP2 -> www/nghttp2

    // devel/pcre2 and devel/pkgconf, but not devel/nonexistent
    assert_eq!(stats.port_deps_indexed, 2);

    let dep_types: Vec<(String, String)> = conn
        .prepare("SELECT dep_origin, dep_type FROM port_deps WHERE port_origin = 'www/nginx' ORDER BY dep_origin")
        .unwrap()
        .query_map([], |r| Ok((r.get(0)?, r.get(1)?)))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    assert_eq!(
        dep_types,
        vec![
            ("devel/pcre2".to_string(), "LIB".to_string()),
            ("devel/pkgconf".to_string(), "BUILD".to_string()),
        ]
    );

    // `HTTP2_RUN_DEPENDS` is option-conditional and must not also be recorded
    // as an unconditional dependency
    let nghttp2_unconditional: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM port_deps WHERE dep_origin = 'www/nghttp2'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(nghttp2_unconditional, 0);

    // Query SQLite database directly to verify values
    let count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM ports WHERE origin = 'www/nginx'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(count, 1);

    let http2_default: i32 = conn
        .query_row(
            "SELECT default_state FROM options WHERE port_origin = 'www/nginx' AND option_name = 'HTTP2'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(http2_default, 1);

    let debug_default: i32 = conn
        .query_row(
            "SELECT default_state FROM options WHERE port_origin = 'www/nginx' AND option_name = 'DEBUG'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(debug_default, 0);
}

// ============================================================================
// 3b. THE MAKEFILE SWEEP MEETS CONSTRUCTS IT CANNOT EVALUATE
//
// The indexer is a line-oriented regex sweep, not bmake. It never evaluates
// `.if`, never expands `.for`, and never follows `.include` or `MASTERDIR`.
// That is deliberate: `make describe-json` is run against the ports actually
// targeted and is authoritative for which options exist, so the sweep only has
// to be fast and approximately right.
//
// What follows pins what it does with the constructs it cannot evaluate, so
// that changing any of it is a visible decision rather than an accident. Each
// test says which way the approximation errs, because the two directions are
// not equally safe: collecting an option that does not exist is harmless —
// `bsd.options.mk` guards `OPTIONS_FILE_SET` with a membership test — whereas
// missing one that does is what keeps `config-conditional` re-prompting.
// ============================================================================

/// A slave port keeps its options in the master's Makefile, so the sweep, which
/// reads only the port's own directory, finds none of them.
///
/// Measured against the tree: 1,127 ports set `MASTERDIR`, and 1,043 of them
/// (93%) come out of indexing with no options at all. `describe-json` supplies
/// the names and defaults for whichever of them get targeted. What it cannot
/// supply is descriptions or `SINGLE`/`MULTI`/`RADIO` grouping, so a slave port
/// is configured as a flat list even where its master has a radio group — the
/// degradation this test exists to make explicit rather than incidental.
#[test]
fn test_a_slave_port_inherits_no_options_from_its_master() {
    let temp = TempDir::new("slave_port");
    let ports_root = temp.path.join("ports");

    let master = ports_root.join("mail").join("postfixadmin33");
    fs::create_dir_all(&master).unwrap();
    fs::write(
        master.join("Makefile"),
        r#"
PORTNAME=   postfixadmin
PORTVERSION=3.3.13
COMMENT=    Web based virtual user administration

OPTIONS_DEFINE=     DOCS FPM
OPTIONS_SINGLE=     DB
OPTIONS_SINGLE_DB=  MYSQL PGSQL
OPTIONS_DEFAULT=    DOCS MYSQL

FPM_DESC=   Use PHP-FPM
MYSQL_DESC= MySQL backend
PGSQL_DESC= PostgreSQL backend
"#,
    )
    .unwrap();

    // The real shape of a slave: a suffix, a pointer, and an include
    let slave = ports_root.join("mail").join("postfixadmin33-lite");
    fs::create_dir_all(&slave).unwrap();
    fs::write(
        slave.join("Makefile"),
        r#"
PKGNAMESUFFIX=  -lite
MASTERDIR=      ${.CURDIR}/../postfixadmin33
.include "${MASTERDIR}/Makefile"
"#,
    )
    .unwrap();

    let mut conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();
    indexer::index_ports_dir(&mut conn, &ports_root).unwrap();

    let options_of = |origin: &str| -> Vec<String> {
        conn.prepare("SELECT option_name FROM options WHERE port_origin = ?1 ORDER BY option_name")
            .unwrap()
            .query_map([origin], |r| r.get(0))
            .unwrap()
            .map(|r| r.unwrap())
            .collect()
    };

    assert_eq!(
        options_of("mail/postfixadmin33"),
        vec!["DOCS", "FPM", "MYSQL", "PGSQL"],
        "the master's own options are found normally"
    );
    assert!(
        options_of("mail/postfixadmin33-lite").is_empty(),
        "the sweep does not follow MASTERDIR, so the slave has nothing"
    );

    // The slave is still indexed as a port; only its options are missing, which
    // is what makes the omission silent rather than obvious.
    let indexed: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM ports WHERE origin = 'mail/postfixadmin33-lite'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(indexed, 1);

    // ---- what describe-json then rescues, and what it does not ----
    cache_details(
        &conn,
        "mail/postfixadmin33-lite",
        "postfixadmin-lite-3.3.13",
        "DOCS FPM MYSQL PGSQL",
        "DOCS MYSQL",
    );

    let graph = DependencyGraph::load_from_db(
        &conn,
        &["mail/postfixadmin33-lite".to_string()],
        &SystemOptions::default(),
        false,
    )
    .unwrap();

    let opt = |name: &str| {
        graph
            .option_nodes
            .iter()
            .find(|o| o.name == name)
            .unwrap_or_else(|| panic!("{name} missing after the merge"))
    };

    // Rescued: every option exists, with the tree's defaults
    assert_eq!(graph.option_nodes.len(), 4);
    assert!(opt("DOCS").enabled);
    assert!(opt("MYSQL").enabled);
    assert!(!opt("FPM").enabled);
    assert!(!opt("PGSQL").enabled);

    // Not rescued: describe-json carries neither of these, and the index had
    // nothing to match them against. MYSQL/PGSQL are a radio group in the
    // master and are presented here as two independent checkboxes.
    assert_eq!(opt("MYSQL").description, "");
    assert_eq!(opt("PGSQL").description, "");
    assert_eq!(opt("MYSQL").group_type, "DEFINE");
    assert_eq!(opt("PGSQL").group_type, "DEFINE");
    assert_eq!(opt("MYSQL").group_name, "");
}

/// Conditionals are not evaluated, so an option defined in either branch of an
/// `.if` is collected from *both*. It errs towards over-collecting, which is
/// the harmless direction.
#[test]
fn test_options_from_every_branch_of_a_conditional_are_collected() {
    let temp = TempDir::new("branches");
    let ports_root = temp.path.join("ports");
    let port = ports_root.join("www").join("branchy");
    fs::create_dir_all(&port).unwrap();

    fs::write(
        port.join("Makefile"),
        r#"
PORTNAME=   branchy
PORTVERSION=1.0
COMMENT=    Defines different options per architecture

OPTIONS_DEFINE= COMMON
.if ${ARCH} == amd64
OPTIONS_DEFINE+=    SIMD
.else
OPTIONS_DEFINE+=    PORTABLE
.endif

.if ${OPSYS} == FreeBSD
OPTIONS_DEFINE+=    JAIL
.endif
"#,
    )
    .unwrap();

    let mut conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();
    indexer::index_ports_dir(&mut conn, &ports_root).unwrap();

    let names: Vec<String> = conn
        .prepare("SELECT option_name FROM options WHERE port_origin = 'www/branchy' ORDER BY option_name")
        .unwrap()
        .query_map([], |r| r.get(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();

    assert_eq!(
        names,
        vec!["COMMON", "JAIL", "PORTABLE", "SIMD"],
        "both arms of the .if are taken, and the .endif is not honoured"
    );
}

/// Scalar assignments are last-one-wins across branches, and the operator is
/// honoured rather than everything being treated as `+=`.
///
/// Treating them all as `+=` would accumulate every branch at once, and any
/// expansion using the variable would come out as nonsense — the
/// `subversion-lts-lts-lts-lts-lts` case the parser documents.
#[test]
fn test_a_variable_set_in_several_branches_takes_the_last_one() {
    let temp = TempDir::new("last_wins");
    let ports_root = temp.path.join("ports");
    let port = ports_root.join("www").join("varsy");
    fs::create_dir_all(&port).unwrap();

    fs::write(
        port.join("Makefile"),
        r#"
PORTNAME=   varsy
.if ${FLAVOR} == lts
SUFFIX=     -lts
.else
SUFFIX=     -current
.endif
PORTVERSION=1.0${SUFFIX}
COMMENT=    Version carries whichever suffix was assigned last
"#,
    )
    .unwrap();

    let mut conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();
    indexer::index_ports_dir(&mut conn, &ports_root).unwrap();

    let version: String = conn
        .query_row(
            "SELECT version FROM ports WHERE origin = 'www/varsy'",
            [],
            |r| r.get(0),
        )
        .unwrap();

    assert_eq!(
        version, "1.0-current",
        "the last assignment wins; concatenating both would give 1.0-lts-current"
    );
}

/// `.for` loops are not expanded, so options generated by one are dropped
/// entirely — the *unsafe* direction, and the reason describe-json is not
/// optional for these ports.
///
/// The loop variable is never bound, so `${O}` expands to the empty string and
/// fails the option-name check. 60 ports in the tree build options this way.
#[test]
fn test_options_generated_by_a_for_loop_are_dropped() {
    let temp = TempDir::new("for_loop");
    let ports_root = temp.path.join("ports");
    let port = ports_root.join("www").join("loopy");
    fs::create_dir_all(&port).unwrap();

    fs::write(
        port.join("Makefile"),
        r#"
PORTNAME=   loopy
PORTVERSION=1.0
COMMENT=    Builds its option list with a .for

OPTIONS_DEFINE= KEPT
.for O in ALPHA BETA GAMMA
OPTIONS_DEFINE+=    ${O}
${O}_DESC=          Support for ${O}
.endfor
"#,
    )
    .unwrap();

    let mut conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();
    indexer::index_ports_dir(&mut conn, &ports_root).unwrap();

    let names: Vec<String> = conn
        .prepare(
            "SELECT option_name FROM options WHERE port_origin = 'www/loopy' ORDER BY option_name",
        )
        .unwrap()
        .query_map([], |r| r.get(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();

    assert_eq!(
        names,
        vec!["KEPT"],
        "ALPHA/BETA/GAMMA are lost: the loop variable is unbound, so ${{O}} \
         expands to nothing and the empty name is rejected"
    );
}

// ============================================================================
// 4. GRAPH ENGINE TESTS (Radio Buttons, Search, Expansion)
// ============================================================================

#[test]
fn test_graph_radio_group_mutual_exclusion() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('databases/db', 'db', '1.0', 'Database')",
        [],
    ).unwrap();

    // Insert two options in the same SINGLE group
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('databases/db', 'ENGINE_A', 1, 'Engine A', 'SINGLE', 'ENGINE'),
                ('databases/db', 'ENGINE_B', 0, 'Engine B', 'SINGLE', 'ENGINE')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["databases/db".to_string()], &sys_opts, false)
            .unwrap();

    // Verify initial states
    assert!(graph.option_nodes[0].enabled); // ENGINE_A
    assert!(!graph.option_nodes[1].enabled); // ENGINE_B

    // Row 0 is the root Port (already expanded by default).
    // Row 1 is ENGINE_A, Row 2 is ENGINE_B.
    // Toggle ENGINE_B at row 2 directly:
    graph.toggle_option(2);

    // Verify mutual exclusion: ENGINE_B becomes enabled, ENGINE_A becomes disabled
    assert!(!graph.option_nodes[0].enabled); // ENGINE_A disabled
    assert!(graph.option_nodes[1].enabled); // ENGINE_B enabled
}

/// Search narrows by port origin. An option name is not searched — this test
/// used to assert the opposite, that searching "SSL" kept the OPENSSL option
/// row, which is what left options stranded without their ports.
#[test]
fn test_graph_search_filtering() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('net/curl', 'curl', '8.0', 'Data transfer tool')",
        [],
    ).unwrap();

    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('net/curl', 'HTTP2', 1, 'Enable HTTP2 support', 'DEFINE', ''),
                ('net/curl', 'OPENSSL', 1, 'Use OpenSSL backend', 'DEFINE', ''),
                ('net/curl', 'COOKIES', 0, 'Enable Cookie support', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["net/curl".to_string()], &sys_opts, false).unwrap();

    // Expand all nodes
    graph.expand_all();
    let total_unfiltered_rows = graph.visible_rows.len();

    // "SSL" appears in an option name and an option description, but not in the
    // origin, so it matches nothing at all
    graph.search_query = "SSL".to_string();
    graph.rebuild_visible_rows();
    assert!(
        graph.visible_rows.is_empty(),
        "an option name must not pull its port into the results"
    );

    // The origin does match, and brings the whole port back with it
    graph.search_query = "curl".to_string();
    graph.rebuild_visible_rows();
    assert_eq!(graph.visible_rows.len(), total_unfiltered_rows);
    assert!(graph.visible_rows.iter().any(|r| match &r.kind {
        RowKind::Option { name, .. } => name == "OPENSSL",
        _ => false,
    }));

    // Clear search filter
    graph.search_query.clear();
    graph.rebuild_visible_rows();
    assert_eq!(graph.visible_rows.len(), total_unfiltered_rows);
}

#[test]
fn test_unknown_port_returns_error() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let sys_opts = SystemOptions::default();
    let result =
        DependencyGraph::load_from_db(&conn, &["nonexistent/port".to_string()], &sys_opts, false);

    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found"));
}

#[test]
fn test_graph_glob_pattern_resolution() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES
         ('www/py-django', 'py-django', '4.2', 'Web Framework'),
         ('www/py-requests', 'py-requests', '2.31', 'HTTP Library')",
        [],
    )
    .unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/py-*".to_string()];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    assert_eq!(graph.requested_ports().count(), 2);
    assert!(graph.root_origin.contains("2 ports matched"));
}

#[test]
fn test_pattern_matching_zero_ports_returns_error() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["nonexistent/*".to_string()];

    let result = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false);

    // Bails when zero ports match across all provided patterns
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found for pattern(s): 'nonexistent/*'"));
}

#[test]
fn test_mixed_delimiter_ports_file_parsing() {
    let temp = TempDir::new("file_parsing");
    let ports_file = temp.path.join("my_ports.txt");

    // File containing mixed commas, tabs, spaces, newlines, full comments, and inline comments
    let file_content = r#"
# Core infrastructure
www/apache24, databases/postgresql16-server  lang/python311 # inline comment

# Wildcards
www/py-*, net/curl
"#;
    fs::write(&ports_file, file_content).unwrap();

    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES
         ('www/apache24', 'apache', '2.4', 'Server'),
         ('databases/postgresql16-server', 'pg', '16.0', 'DB'),
         ('lang/python311', 'python', '3.11', 'Lang'),
         ('www/py-django', 'django', '4.2', 'Web'),
         ('net/curl', 'curl', '8.0', 'Tool')",
        [],
    )
    .unwrap();

    let targets = parse_ports_file(&ports_file).unwrap();

    let sys_opts = SystemOptions::default();
    let graph = DependencyGraph::load_from_db(&conn, &targets, &sys_opts, false).unwrap();

    // Should resolve all 5 matching ports cleanly
    assert_eq!(graph.requested_ports().count(), 5);
}

#[test]
fn test_multiple_ports_with_one_unknown_returns_error() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/apache24".to_string(), "invalid/unknown".to_string()];

    let result = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false);

    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found for pattern(s): 'invalid/unknown'"));
}

#[test]
fn test_ignore_missing_flag_warns_and_continues() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/apache24".to_string(), "invalid/unknown".to_string()];

    // With ignore_missing = true, valid port loads cleanly and doesn't bail out
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, true).unwrap();
    assert_eq!(graph.requested_ports().count(), 1);
}

// ============================================================================
// 5. DUPLICATE PORT TESTS (Shared option state across repeated occurrences)
// ============================================================================

/// Two roots that both depend on `devel/shared`, which itself carries options.
fn shared_dependency_db() -> Connection {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES
         ('www/root1', 'root1', '1.0', 'First root'),
         ('www/root2', 'root2', '1.0', 'Second root'),
         ('devel/shared', 'shared', '1.0', 'Shared dependency')",
        [],
    )
    .unwrap();

    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('www/root1', 'USE_SHARED', 1, 'Pull in shared', 'DEFINE', ''),
                ('www/root2', 'ALSO_SHARED', 1, 'Pull in shared', 'DEFINE', ''),
                ('devel/shared', 'THREADS', 0, 'Threading support', 'DEFINE', ''),
                ('devel/shared', 'ENGINE_A', 1, 'Engine A', 'SINGLE', 'ENGINE'),
                ('devel/shared', 'ENGINE_B', 0, 'Engine B', 'SINGLE', 'ENGINE')",
        [],
    )
    .unwrap();

    conn.execute(
        "INSERT INTO option_deps (port_origin, option_name, dep_origin, dep_type) VALUES
         ('www/root1', 'USE_SHARED', 'devel/shared', 'RUN'),
         ('www/root2', 'ALSO_SHARED', 'devel/shared', 'RUN')",
        [],
    )
    .unwrap();

    conn
}

// ============================================================================
// 4b. DEPENDENCY WALK (cycles, depth, unconditional dependencies)
// ============================================================================

/// Builds a database from `(origin, option, dep)` option-conditional edges and
/// `(origin, dep)` unconditional ones. Every named port gets one option so the
/// tree has something to show.
fn dep_graph_db(option_edges: &[(&str, &str, &str)], port_edges: &[(&str, &str)]) -> Connection {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let mut origins: Vec<&str> = Vec::new();
    for (from, _, to) in option_edges {
        origins.push(from);
        origins.push(to);
    }
    for (from, to) in port_edges {
        origins.push(from);
        origins.push(to);
    }
    origins.sort_unstable();
    origins.dedup();

    for origin in &origins {
        let name = origin.split('/').nth(1).unwrap();
        conn.execute(
            "INSERT INTO ports (origin, name, version, comment) VALUES (?1, ?2, '1.0', '')",
            rusqlite::params![origin, name],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
             VALUES (?1, 'DOCS', 1, '', 'DEFINE', '')",
            rusqlite::params![origin],
        )
        .unwrap();
    }

    for (from, opt, to) in option_edges {
        conn.execute(
            "INSERT OR IGNORE INTO options (port_origin, option_name, default_state, description, group_type, group_name)
             VALUES (?1, ?2, 1, '', 'DEFINE', '')",
            rusqlite::params![from, opt],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO option_deps (port_origin, option_name, dep_origin, dep_type) VALUES (?1, ?2, ?3, 'RUN')",
            rusqlite::params![from, opt, to],
        )
        .unwrap();
    }

    for (from, to) in port_edges {
        conn.execute(
            "INSERT INTO port_deps (port_origin, dep_origin, dep_type) VALUES (?1, ?2, 'LIB')",
            rusqlite::params![from, to],
        )
        .unwrap();
    }

    conn
}

fn origins_in_list(graph: &DependencyGraph) -> Vec<String> {
    graph.ports.iter().map(|p| p.origin.clone()).collect()
}

/// The list is an index, so it reads alphabetically and holds each port once.
#[test]
fn test_port_list_is_alphabetised_and_holds_each_port_once() {
    let conn = dep_graph_db(
        &[("www/nginx", "SSL", "security/openssl")],
        &[
            ("www/nginx", "devel/pcre2"),
            ("devel/pcre2", "devel/pkgconf"),
        ],
    );
    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/nginx".to_string()], &sys_opts, false).unwrap();

    assert_eq!(
        origins_in_list(&graph),
        vec![
            "devel/pcre2",
            "devel/pkgconf",
            "security/openssl",
            "www/nginx"
        ]
    );

    // by_origin must agree with the list it indexes
    for (i, port) in graph.ports.iter().enumerate() {
        assert_eq!(graph.port_index(&port.origin), Some(i));
    }
}

/// A dependency cycle terminates by reaching a port already collected, not by
/// hitting a depth limit — and produces no duplicate entry.
#[test]
fn test_dependency_cycle_terminates_without_duplicating_a_port() {
    let conn = dep_graph_db(
        &[
            ("www/a", "NEEDS_B", "www/b"),
            ("www/b", "NEEDS_C", "www/c"),
            ("www/c", "NEEDS_A", "www/a"),
        ],
        &[],
    );
    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/a".to_string()], &sys_opts, false).unwrap();

    assert_eq!(origins_in_list(&graph), vec!["www/a", "www/b", "www/c"]);
    assert_eq!(
        graph.ports.len(),
        3,
        "the cycle must not add a fourth entry"
    );

    // The edge closing the loop is still recorded, as a reverse reference
    let a = &graph.ports[graph.port_index("www/a").unwrap()];
    assert_eq!(a.required_by.len(), 1);
    assert_eq!(a.required_by[0].origin, "www/c");
    assert_eq!(a.required_by[0].via_option.as_deref(), Some("NEEDS_A"));
}

/// `required by` is the exact inverse of every forward edge, conditional and
/// unconditional, and records which option made it conditional.
#[test]
fn test_required_by_inverts_both_kinds_of_edge() {
    let conn = dep_graph_db(
        &[("www/app", "SSL", "security/openssl")],
        &[("www/app", "devel/pcre2"), ("www/other", "devel/pcre2")],
    );
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/app".to_string(), "www/other".to_string()];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    let openssl = &graph.ports[graph.port_index("security/openssl").unwrap()];
    assert_eq!(openssl.required_by.len(), 1);
    assert_eq!(openssl.required_by[0].origin, "www/app");
    assert_eq!(openssl.required_by[0].via_option.as_deref(), Some("SSL"));

    // Two parents, both unconditional, sorted by origin
    let pcre2 = &graph.ports[graph.port_index("devel/pcre2").unwrap()];
    let parents: Vec<(&str, Option<&str>)> = pcre2
        .required_by
        .iter()
        .map(|r| (r.origin.as_str(), r.via_option.as_deref()))
        .collect();
    assert_eq!(parents, vec![("www/app", None), ("www/other", None)]);

    // A port nobody depends on has an empty list
    let app = &graph.ports[graph.port_index("www/app").unwrap()];
    assert!(app.required_by.is_empty());
}

/// Ports named on the command line are white; everything pulled in is yellow.
#[test]
fn test_provenance_marks_requested_ports_separately() {
    let conn = dep_graph_db(&[], &[("www/app", "devel/pcre2")]);
    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();

    let app = &graph.ports[graph.port_index("www/app").unwrap()];
    let pcre2 = &graph.ports[graph.port_index("devel/pcre2").unwrap()];

    assert_eq!(app.provenance, Provenance::Requested);
    assert_eq!(pcre2.provenance, Provenance::Dependency);
    assert_eq!(graph.requested_ports().count(), 1);

    // Requested ports open on arrival so the list is usable immediately
    assert!(app.is_expanded);
    assert!(!pcre2.is_expanded);
}

/// Asking for a port by name outranks having it dragged in as a dependency.
#[test]
fn test_requested_outranks_being_a_dependency() {
    let conn = dep_graph_db(&[], &[("www/app", "devel/pcre2")]);
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/app".to_string(), "devel/pcre2".to_string()];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    let pcre2 = &graph.ports[graph.port_index("devel/pcre2").unwrap()];
    assert_eq!(pcre2.provenance, Provenance::Requested);
    // ...and it is still recorded as a dependency of www/app
    assert_eq!(pcre2.required_by.len(), 1);
}

/// Chains deeper than the old fixed cap are walked all the way down, so every
/// port reachable from a target gets an options file.
#[test]
fn test_dependency_chain_is_walked_past_the_old_depth_cap() {
    let chain: Vec<(String, String, String)> = (0..12)
        .map(|i| {
            (
                format!("www/p{i}"),
                "NEEDS_NEXT".to_string(),
                format!("www/p{}", i + 1),
            )
        })
        .collect();
    let edges: Vec<(&str, &str, &str)> = chain
        .iter()
        .map(|(a, b, c)| (a.as_str(), b.as_str(), c.as_str()))
        .collect();

    let conn = dep_graph_db(&edges, &[]);
    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/p0".to_string()], &sys_opts, false).unwrap();

    assert_eq!(origins_in_list(&graph).len(), 13, "p0 through p12");
    assert!(graph.ports.iter().any(|p| p.origin == "www/p12"));
}

/// Unconditional dependencies are walked like any other edge and surface under
/// a `requires` section, which is a grouping row and never an exported option.
#[test]
fn test_unconditional_dependencies_are_walked_but_never_exported() {
    let temp = TempDir::new("requires_export");
    let options_dir = temp.path.join("ports");

    let conn = dep_graph_db(
        &[("www/app", "SSL", "security/openssl")],
        &[("www/app", "devel/pcre2"), ("devel/pcre2", "devel/pkgconf")],
    );
    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();

    // Reached transitively through two unconditional edges
    assert!(graph.ports.iter().any(|p| p.origin == "devel/pkgconf"));

    graph.expand_all();
    let requires_headers = graph
        .visible_rows
        .iter()
        .filter(|r| {
            matches!(
                &r.kind,
                RowKind::SectionHeader {
                    kind: SectionKind::Requires,
                    ..
                }
            )
        })
        .count();
    assert_eq!(requires_headers, 2, "one for www/app, one for devel/pcre2");

    exporter::export_options(&graph, &options_dir, false, None).unwrap();

    // Section headers are presentation only; nothing about them is written
    for port in [
        "www_app",
        "security_openssl",
        "devel_pcre2",
        "devel_pkgconf",
    ] {
        let content = fs::read_to_string(options_dir.join(port).join("options")).unwrap();
        assert!(
            !content.contains("requires"),
            "{port} leaked a section header into its options file"
        );
    }
    let app = fs::read_to_string(options_dir.join("www_app").join("options")).unwrap();
    assert!(app.contains("_FILE_COMPLETE_OPTIONS_LIST=DOCS SSL"));
}

/// A section header groups relationships; pressing Space on it must not toggle
/// anything or mark the graph dirty.
#[test]
fn test_section_header_is_not_toggleable() {
    let conn = dep_graph_db(&[], &[("www/app", "devel/pcre2")]);
    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();
    graph.expand_all();

    for row in 0..graph.visible_rows.len() {
        if matches!(graph.visible_rows[row].kind, RowKind::SectionHeader { .. }) {
            graph.toggle_option(row);
        }
    }

    assert!(!graph.is_dirty());
}

/// Relationship rows are jump targets, and every target resolves to an entry.
#[test]
fn test_relationship_rows_carry_resolvable_jump_targets() {
    let conn = dep_graph_db(
        &[("www/app", "SSL", "security/openssl")],
        &[("www/app", "devel/pcre2")],
    );
    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();
    graph.expand_all();

    let mut targets: Vec<&str> = graph
        .visible_rows
        .iter()
        .filter_map(|r| r.kind.jump_target())
        .collect();
    targets.sort_unstable();
    targets.dedup();
    assert_eq!(targets, vec!["devel/pcre2", "security/openssl", "www/app"]);

    for target in targets {
        assert!(graph.port_index(target).is_some(), "{target} not in list");
    }

    // Port and option rows are not jump targets
    assert!(graph
        .visible_rows
        .iter()
        .filter(|r| matches!(r.kind, RowKind::Port { .. } | RowKind::Option { .. }))
        .all(|r| r.kind.jump_target().is_none()));
}

// ============================================================================
// 4d. PORT DETAILS FROM THE TREE (describe-json)
// ============================================================================

/// Writes a `port_details` row as though `make describe-json` had been run.
fn cache_details(conn: &Connection, origin: &str, pkgname: &str, complete: &str, defaults: &str) {
    let pkgbase = pkgname.rsplit_once('-').map(|(b, _)| b).unwrap_or(pkgname);
    conn.execute(
        "INSERT OR REPLACE INTO port_details
         (port_origin, pkgbase, pkgname, complete_options_list, options_default, source_mtime)
         VALUES (?1, ?2, ?3, ?4, ?5, 0)",
        rusqlite::params![origin, pkgbase, pkgname, complete, defaults],
    )
    .unwrap();
}

#[test]
fn test_describe_json_parses_an_unflavoured_port() {
    let json = r#"{ "uses":["cpe"], "complete_options_list":["DOCS","SSL","X11"],
        "options_default":["SSL"], "pkgbase":"nginx", "pkgname":"nginx-1.24.0_2",
        "portversion":"1.24.0", "www":"https://nginx.org" }"#;

    let d = describe::parse_describe_json(json, "www/nginx", 1234).unwrap();

    assert_eq!(d.pkgname, "nginx-1.24.0_2");
    assert_eq!(d.pkgbase, "nginx");
    assert_eq!(d.complete_options_list, vec!["DOCS", "SSL", "X11"]);
    assert_eq!(d.options_default, vec!["SSL"]);
    assert_eq!(d.source_mtime, 1234);
}

/// A port with FLAVORS emits one document per flavour, keyed by flavour name.
#[test]
fn test_describe_json_parses_a_flavoured_port() {
    let json = r#"{
        "py311-django": { "complete_options_list":["DOCS"], "options_default":[""],
                          "pkgbase":"py311-django", "pkgname":"py311-django-4.2.11" },
        "py39-django":  { "complete_options_list":["DOCS"], "options_default":[""],
                          "pkgbase":"py39-django", "pkgname":"py39-django-4.2.11" }
    }"#;

    let d = describe::parse_describe_json(json, "www/py-django", 7).unwrap();

    assert!(d.pkgname.ends_with("-django-4.2.11"));
    assert_eq!(d.complete_options_list, vec!["DOCS"]);
    // An empty make variable renders as [""], which is not an option named ""
    assert!(d.options_default.is_empty());
}

#[test]
fn test_describe_json_rejects_unusable_output() {
    assert!(describe::parse_describe_json("not json", "www/x", 0).is_err());
    assert!(describe::parse_describe_json("{}", "www/x", 0).is_err());
    assert!(describe::parse_describe_json(r#"{"pkgname":""}"#, "www/x", 0).is_err());
}

/// An option the Makefile sweep could not see still reaches the options file.
///
/// `security/ossec-hids-agent` is a measured instance: it inherits through
/// `MASTERDIR`, the sweep finds no options for it at all, and the tree reports
/// `DOCS INOTIFY LUA`. Rare — about 1% of ports — but while it lasts
/// `config-conditional` keeps re-opening the dialog for that port.
#[test]
fn test_options_only_the_tree_knows_about_are_written() {
    let temp = TempDir::new("described_options");
    let options_dir = temp.path.join("ports");

    let conn = dep_graph_db(&[], &[]);
    conn.execute(
        "INSERT INTO ports (origin, name, version, comment)
         VALUES ('security/ossec-hids-agent', 'ossec-hids-agent', 'latest', '')",
        [],
    )
    .unwrap();
    // The sweep finds nothing: the options live in the master's Makefile
    // What the tree reports, plus a PKGNAME the sweep could not reconstruct
    cache_details(
        &conn,
        "security/ossec-hids-agent",
        "ossec-hids-agent-3.8.0",
        "DOCS INOTIFY LUA",
        "INOTIFY",
    );

    let sys_opts = SystemOptions::default();
    let graph = DependencyGraph::load_from_db(
        &conn,
        &["security/ossec-hids-agent".to_string()],
        &sys_opts,
        false,
    )
    .unwrap();

    exporter::export_options(&graph, &options_dir, false, None).unwrap();
    let content = fs::read_to_string(
        options_dir
            .join("security_ossec-hids-agent")
            .join("options"),
    )
    .unwrap();

    // The real PKGNAME, not a reconstruction
    assert!(content.contains("_OPTIONS_READ=ossec-hids-agent-3.8.0"));
    assert!(content.contains("_FILE_COMPLETE_OPTIONS_LIST=DOCS INOTIFY LUA"));

    // Every option named, or config-conditional prompts again
    for opt in ["DOCS", "INOTIFY", "LUA"] {
        assert!(
            content.contains(&format!("OPTIONS_FILE_SET+={opt}"))
                || content.contains(&format!("OPTIONS_FILE_UNSET+={opt}")),
            "{opt} missing from the options file"
        );
    }

    // Defaults come from the tree, and DOCS is on even though OPTIONS_DEFAULT
    // does not list it — bsd.options.mk turns it on whenever a port defines it
    assert!(content.contains("OPTIONS_FILE_SET+=DOCS"));
    assert!(content.contains("OPTIONS_FILE_SET+=INOTIFY"));
    assert!(content.contains("OPTIONS_FILE_UNSET+=LUA"));
}

/// An option the tree reports but the regex missed must not be written as UNSET
/// when it is on by default — that would silently turn it off.
#[test]
fn test_a_defaulted_option_the_regex_missed_is_not_silently_disabled() {
    let temp = TempDir::new("described_defaults");
    let options_dir = temp.path.join("ports");

    let conn = dep_graph_db(&[], &[]);
    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/app2', 'app2', '1.0', '')",
        [],
    )
    .unwrap();
    cache_details(&conn, "www/app2", "app2-1.0", "ALPHA BETA", "ALPHA");

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/app2".to_string()], &sys_opts, false).unwrap();

    exporter::export_options(&graph, &options_dir, false, None).unwrap();
    let content = fs::read_to_string(options_dir.join("www_app2").join("options")).unwrap();

    assert!(content.contains("OPTIONS_FILE_SET+=ALPHA"));
    assert!(content.contains("OPTIONS_FILE_UNSET+=BETA"));
}

/// Descriptions and radio grouping are not in describe-json, so they keep
/// coming from the Makefile parse and must survive the merge.
#[test]
fn test_merge_keeps_descriptions_and_grouping_from_the_index() {
    let conn = dep_graph_db(&[], &[]);
    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/app3', 'app3', '1.0', '')",
        [],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('www/app3', 'ENGINE_A', 1, 'Engine A', 'SINGLE', 'ENGINE'),
                ('www/app3', 'ENGINE_B', 0, 'Engine B', 'SINGLE', 'ENGINE')",
        [],
    )
    .unwrap();
    cache_details(
        &conn,
        "www/app3",
        "app3-1.0",
        "ENGINE_A ENGINE_B HIDDEN",
        "ENGINE_A",
    );

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/app3".to_string()], &sys_opts, false).unwrap();

    let by_name = |name: &str| {
        graph
            .option_nodes
            .iter()
            .find(|o| o.name == name)
            .unwrap_or_else(|| panic!("{name} missing"))
    };

    assert_eq!(by_name("ENGINE_A").description, "Engine A");
    assert_eq!(by_name("ENGINE_A").group_type, "SINGLE");
    assert_eq!(by_name("ENGINE_A").group_name, "ENGINE");

    // The one only the tree knew about arrives ungrouped and undescribed
    assert_eq!(by_name("HIDDEN").description, "");
    assert_eq!(by_name("HIDDEN").group_type, "DEFINE");
    assert!(!by_name("HIDDEN").enabled);
}

// ============================================================================
// 4c. LIVE REACHABILITY (ports appear and vanish as options change)
// ============================================================================

fn listed_origins(graph: &DependencyGraph) -> Vec<String> {
    graph
        .visible_rows
        .iter()
        .filter_map(|r| match &r.kind {
            RowKind::Port { origin, .. } => Some(origin.clone()),
            _ => None,
        })
        .collect()
}

/// Turning an option off drops the port it pulled in, and everything only that
/// port pulled in, all the way down.
#[test]
fn test_disabling_an_option_strands_its_whole_subtree() {
    let conn = dep_graph_db(
        &[("www/app", "LUA", "lang/lua54")],
        &[("lang/lua54", "devel/readline"), ("www/app", "devel/pcre2")],
    );
    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();

    // LUA defaults on, so the whole chain is pulled in
    assert_eq!(
        listed_origins(&graph),
        vec!["devel/pcre2", "devel/readline", "lang/lua54", "www/app"]
    );

    let row = find_option_row(&graph, "www/app", "LUA");
    graph.toggle_option(row);

    // lang/lua54 goes, and devel/readline goes with it; devel/pcre2 stays
    // because www/app requires it unconditionally
    assert_eq!(listed_origins(&graph), vec!["devel/pcre2", "www/app"]);
    assert!(!graph.is_live("lang/lua54"));
    assert!(!graph.is_live("devel/readline"));

    // Turning it back on restores the whole chain
    let row = find_option_row(&graph, "www/app", "LUA");
    graph.toggle_option(row);
    assert_eq!(
        listed_origins(&graph),
        vec!["devel/pcre2", "devel/readline", "lang/lua54", "www/app"]
    );
}

/// A port still pulled in by some other route does not vanish.
#[test]
fn test_a_port_reached_another_way_survives() {
    let conn = dep_graph_db(
        &[("www/app", "SSL", "security/openssl")],
        &[("www/other", "security/openssl")],
    );
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/app".to_string(), "www/other".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    let row = find_option_row(&graph, "www/app", "SSL");
    graph.toggle_option(row);

    assert!(
        graph.is_live("security/openssl"),
        "www/other still requires it unconditionally"
    );
}

/// Selections for a stranded port survive in memory, so bringing it back does
/// not silently reset what was chosen for it.
#[test]
fn test_option_state_survives_a_port_leaving_and_returning() {
    let conn = dep_graph_db(&[("www/app", "LUA", "lang/lua54")], &[]);
    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();

    // DOCS defaults on for lang/lua54; turn it off
    graph.set_option_state("lang/lua54", "DOCS", false);
    assert_eq!(states_of(&graph, "lang/lua54", "DOCS"), vec![false]);

    let row = find_option_row(&graph, "www/app", "LUA");
    graph.toggle_option(row);
    assert!(!graph.is_live("lang/lua54"));

    let row = find_option_row(&graph, "www/app", "LUA");
    graph.toggle_option(row);
    assert!(graph.is_live("lang/lua54"));
    assert_eq!(
        states_of(&graph, "lang/lua54", "DOCS"),
        vec![false],
        "the choice made before it was stranded must come back with it"
    );
}

/// A port nothing pulls in is not written, and editing it does not raise the
/// unsaved-changes prompt over a change that would never be saved.
#[test]
fn test_ports_nothing_pulls_in_are_neither_saved_nor_counted_as_dirty() {
    let temp = TempDir::new("live_export");
    let options_dir = temp.path.join("ports");

    let conn = dep_graph_db(&[("www/app", "LUA", "lang/lua54")], &[]);

    // Start with LUA off, so lang/lua54 is out of the list from the beginning
    let mut sys_opts = SystemOptions::default();
    sys_opts.port_overrides.insert(
        "www/app".to_string(),
        [("LUA".to_string(), false)].into_iter().collect(),
    );

    let mut graph =
        DependencyGraph::load_from_db(&conn, &["www/app".to_string()], &sys_opts, false).unwrap();

    assert!(!graph.is_live("lang/lua54"));
    assert_eq!(listed_origins(&graph), vec!["www/app"]);
    assert!(!graph.is_dirty());

    // Editing a port outside the list changes nothing that will be saved
    graph.set_option_state("lang/lua54", "DOCS", false);
    assert!(
        !graph.is_dirty(),
        "an edit to a port nothing pulls in is not an unsaved change"
    );

    exporter::export_options(&graph, &options_dir, false, None).unwrap();
    assert!(options_dir.join("www_app").join("options").exists());
    assert!(
        !options_dir.join("lang_lua54").exists(),
        "a port nothing pulls in must not be written"
    );
}

/// Index of the visible row holding `opt_name` for `origin`. Each port is
/// listed once, so there is exactly one such row when the port is expanded.
fn find_option_row(graph: &DependencyGraph, origin: &str, opt_name: &str) -> usize {
    graph
        .visible_rows
        .iter()
        .position(|row| match row.node_id {
            NodeId::Option(id) => {
                let opt = &graph.option_nodes[id];
                opt.port_origin == origin && opt.name == opt_name
            }
            _ => false,
        })
        .unwrap_or_else(|| panic!("no visible row for {origin}/{opt_name}"))
}

fn states_of(graph: &DependencyGraph, origin: &str, opt_name: &str) -> Vec<bool> {
    graph
        .option_instances(origin, opt_name)
        .into_iter()
        .map(|id| graph.option_nodes[id].enabled)
        .collect()
}

/// A dependency shared by two roots is one entry carrying one set of options,
/// so there is no second copy to keep in sync. Both parents show up in its
/// `required by` instead.
#[test]
fn test_shared_dependency_is_one_entry_naming_both_parents() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();

    let patterns = vec!["www/root1".to_string(), "www/root2".to_string()];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    assert_eq!(
        graph
            .ports
            .iter()
            .filter(|p| p.origin == "devel/shared")
            .count(),
        1
    );
    assert_eq!(graph.option_instances("devel/shared", "THREADS").len(), 1);

    let shared = &graph.ports[graph.port_index("devel/shared").unwrap()];
    let parents: Vec<(&str, Option<&str>)> = shared
        .required_by
        .iter()
        .map(|r| (r.origin.as_str(), r.via_option.as_deref()))
        .collect();
    assert_eq!(
        parents,
        vec![
            ("www/root1", Some("USE_SHARED")),
            ("www/root2", Some("ALSO_SHARED")),
        ]
    );
}

#[test]
fn test_toggling_a_shared_dependency_is_a_single_edit() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();

    let patterns = vec!["www/root1".to_string(), "www/root2".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    assert_eq!(states_of(&graph, "devel/shared", "THREADS"), vec![false]);

    let row = find_option_row(&graph, "devel/shared", "THREADS");
    graph.toggle_option(row);
    assert_eq!(states_of(&graph, "devel/shared", "THREADS"), vec![true]);
    assert!(graph.is_dirty());

    // Toggling back returns the graph to clean
    let row = find_option_row(&graph, "devel/shared", "THREADS");
    graph.toggle_option(row);
    assert_eq!(states_of(&graph, "devel/shared", "THREADS"), vec![false]);
    assert!(!graph.is_dirty());
}

#[test]
fn test_radio_group_on_a_shared_dependency() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();

    let patterns = vec!["www/root1".to_string(), "www/root2".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    assert_eq!(states_of(&graph, "devel/shared", "ENGINE_A"), vec![true]);
    assert_eq!(states_of(&graph, "devel/shared", "ENGINE_B"), vec![false]);

    let row = find_option_row(&graph, "devel/shared", "ENGINE_B");
    graph.toggle_option(row);

    assert_eq!(states_of(&graph, "devel/shared", "ENGINE_A"), vec![false]);
    assert_eq!(states_of(&graph, "devel/shared", "ENGINE_B"), vec![true]);
}

/// A port that is both an explicit target and someone else's dependency is
/// still a single entry, and counts as requested.
#[test]
fn test_explicit_target_that_is_also_a_dependency_stays_one_entry() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();

    let patterns = vec!["www/root1".to_string(), "devel/shared".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    assert_eq!(graph.option_instances("devel/shared", "THREADS").len(), 1);
    let shared = &graph.ports[graph.port_index("devel/shared").unwrap()];
    assert_eq!(shared.provenance, Provenance::Requested);
    assert_eq!(shared.required_by.len(), 1);

    let row = find_option_row(&graph, "devel/shared", "THREADS");
    graph.toggle_option(row);
    assert_eq!(states_of(&graph, "devel/shared", "THREADS"), vec![true]);

    // One row, and it is redrawn with the new state straight away
    let rendered: Vec<bool> = graph
        .visible_rows
        .iter()
        .filter_map(|row| match (&row.kind, &row.node_id) {
            (RowKind::Option { name, enabled, .. }, NodeId::Option(_)) if name == "THREADS" => {
                Some(*enabled)
            }
            _ => None,
        })
        .collect();
    assert_eq!(rendered, vec![true]);
}

#[test]
fn test_exporter_writes_duplicated_port_options_once() {
    let temp = TempDir::new("exporter_duplicates");
    let options_dir = temp.path.join("ports");
    let make_conf_path = temp.path.join("make.conf");

    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/root1".to_string(), "www/root2".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    let row = find_option_row(&graph, "devel/shared", "THREADS");
    graph.toggle_option(row);

    let stats =
        exporter::export_options(&graph, &options_dir, false, Some(&make_conf_path)).unwrap();

    // 3 files (root1, root2, shared); 5 distinct options, not 8 nodes
    assert_eq!(stats.files_written, 3);
    assert_eq!(stats.options_saved, 5);

    let content = fs::read_to_string(options_dir.join("devel_shared").join("options")).unwrap();
    assert_eq!(content.matches("OPTIONS_FILE_SET+=THREADS").count(), 1);
    assert!(!content.contains("OPTIONS_FILE_UNSET+=THREADS"));

    let make_content = fs::read_to_string(&make_conf_path).unwrap();
    assert_eq!(make_content.matches("OPTIONS_SET+=THREADS").count(), 1);
}

// ============================================================================
// 6. UI KEY TESTS (Scope escalation, focus cycle, Ctrl+L recenter)
// ============================================================================

#[test]
fn test_single_row_keys_ignore_repetition() {
    // = and - always act on the row under the cursor, however many times they
    // are pressed
    for repeat in [false, true] {
        assert_eq!(tree_op('=', repeat), Some(TreeOp::ExpandNode));
        assert_eq!(tree_op('-', repeat), Some(TreeOp::CollapseNode));
    }
}

#[test]
fn test_double_tap_escalates_from_section_to_whole_tree() {
    // First press acts on the section under the cursor...
    assert_eq!(tree_op('+', false), Some(TreeOp::ExpandSection));
    assert_eq!(tree_op('_', false), Some(TreeOp::CollapseSection));

    // ...and an immediately following press of the same key widens it
    assert_eq!(tree_op('+', true), Some(TreeOp::ExpandAll));
    assert_eq!(tree_op('_', true), Some(TreeOp::CollapseAll));
}

#[test]
fn test_tree_op_ignores_unrelated_keys() {
    for c in ['a', ' ', 'q', ']', '[', '5'] {
        assert_eq!(
            tree_op(c, false),
            None,
            "key {c:?} should not touch the tree"
        );
        assert_eq!(
            tree_op(c, true),
            None,
            "key {c:?} should not touch the tree"
        );
    }
}

#[test]
fn test_focus_cycles_through_the_list_and_both_buttons() {
    assert_eq!(next_focus(Focus::List), Focus::Ok);
    assert_eq!(next_focus(Focus::Ok), Focus::Cancel);
    assert_eq!(next_focus(Focus::Cancel), Focus::List);

    // Shift+Tab walks it backwards
    assert_eq!(prev_focus(Focus::List), Focus::Cancel);
    assert_eq!(prev_focus(Focus::Cancel), Focus::Ok);
    assert_eq!(prev_focus(Focus::Ok), Focus::List);

    // Round trips
    for f in [Focus::List, Focus::Ok, Focus::Cancel] {
        assert_eq!(prev_focus(next_focus(f)), f);
        assert_eq!(next_focus(next_focus(next_focus(f))), f);
    }
}

// ============================================================================
// 7. SIBLING NAVIGATION TESTS (Shift + Up / Down)
// ============================================================================

#[test]
fn test_next_sibling_skips_over_descendants() {
    //  0: port          depth 0
    //  1:   option      depth 1  <- cursor
    //  2:     dep port  depth 2
    //  3:       option  depth 3
    //  4:   option      depth 1  <- next sibling
    let depths = [0, 1, 2, 3, 1];
    assert_eq!(next_sibling_index(&depths, 1), 4);
}

#[test]
fn test_next_sibling_falls_through_to_the_following_uncle() {
    //  0: port          depth 0
    //  1:   option      depth 1
    //  2:     dep port  depth 2  <- cursor, last child of its parent
    //  3: port          depth 0  <- following uncle
    let depths = [0, 1, 2, 0];
    assert_eq!(next_sibling_index(&depths, 2), 3);
}

#[test]
fn test_next_sibling_stays_put_at_the_end_of_the_tree() {
    let depths = [0, 1, 2];
    assert_eq!(next_sibling_index(&depths, 2), 2);
    assert_eq!(next_sibling_index(&depths, 0), 0);
}

#[test]
fn test_prev_sibling_skips_over_descendants() {
    //  0: port          depth 0
    //  1:   option      depth 1  <- previous sibling
    //  2:     dep port  depth 2
    //  3:   option      depth 1  <- cursor
    let depths = [0, 1, 2, 1];
    assert_eq!(prev_sibling_index(&depths, 3), 1);
}

#[test]
fn test_prev_sibling_falls_through_to_the_parent() {
    //  0: port          depth 0  <- parent
    //  1:   option      depth 1  <- cursor, first child
    let depths = [0, 1];
    assert_eq!(prev_sibling_index(&depths, 1), 0);
}

#[test]
fn test_prev_sibling_stays_put_at_the_top_of_the_tree() {
    let depths = [0, 1, 1];
    assert_eq!(prev_sibling_index(&depths, 0), 0);
}

#[test]
fn test_sibling_navigation_handles_degenerate_input() {
    assert_eq!(next_sibling_index(&[], 0), 0);
    assert_eq!(prev_sibling_index(&[], 0), 0);
    assert_eq!(next_sibling_index(&[0], 5), 5);
    assert_eq!(prev_sibling_index(&[0], 5), 5);
}

#[test]
fn test_sibling_navigation_walks_a_real_list() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/root1".to_string(), "www/root2".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    let depths: Vec<usize> = graph.visible_rows.iter().map(|r| r.depth).collect();
    let port_row = |origin: &str| {
        graph
            .visible_rows
            .iter()
            .position(|r| matches!(&r.kind, RowKind::Port { origin: o, .. } if o == origin))
            .unwrap_or_else(|| panic!("{origin} not listed"))
    };

    // Ports are all at depth 0, so Shift+Down steps alphabetically between them
    let shared = port_row("devel/shared");
    let root1 = port_row("www/root1");
    let root2 = port_row("www/root2");
    assert!(shared < root1 && root1 < root2, "list is alphabetised");

    assert_eq!(next_sibling_index(&depths, shared), root1);
    assert_eq!(next_sibling_index(&depths, root1), root2);
    assert_eq!(prev_sibling_index(&depths, root2), root1);

    // From a row nested under www/root1, Shift+Down falls through to the next
    // port rather than staying inside the block
    assert_eq!(next_sibling_index(&depths, root1 + 1), root2);
}

// ============================================================================
// 8. UNSAVED CHANGES TESTS (Quit confirmation)
// ============================================================================

#[test]
fn test_graph_is_clean_when_first_loaded() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/root1".to_string()];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    assert!(
        !graph.is_dirty(),
        "a freshly loaded tree has nothing to save"
    );
}

#[test]
fn test_toggling_an_option_marks_the_graph_dirty() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/root1".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    let row = find_option_row(&graph, "devel/shared", "THREADS");
    graph.toggle_option(row);
    assert!(graph.is_dirty());

    // Toggling back to the loaded value clears it again, so an undone edit
    // never raises the confirmation box
    graph.toggle_option(row);
    assert!(!graph.is_dirty());
}

#[test]
fn test_radio_switch_marks_the_graph_dirty() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/root1".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();
    graph.expand_all();

    let row = find_option_row(&graph, "devel/shared", "ENGINE_B");
    graph.toggle_option(row);

    assert!(graph.is_dirty());
}

// ============================================================================
// 9. SINGLE-ROW EXPANSION TESTS (= / -)
// ============================================================================

#[test]
fn test_expand_and_collapse_node_affect_only_the_target_row() {
    let conn = shared_dependency_db();
    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/root1".to_string()];
    let mut graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    let root_row = graph
        .visible_rows
        .iter()
        .position(|r| matches!(&r.kind, RowKind::Port { origin, .. } if origin == "www/root1"))
        .expect("requested port should be listed");
    let before = graph.visible_rows.len();

    // www/root1 is requested, so it arrives open
    assert!(graph.visible_rows[root_row].is_expanded);

    graph.collapse_node(root_row);
    assert!(!graph.visible_rows[root_row].is_expanded);
    assert!(
        graph.visible_rows.len() < before,
        "collapsing a port should hide its options"
    );

    // Other ports keep the state they had
    let shared_row = graph
        .visible_rows
        .iter()
        .position(|r| matches!(&r.kind, RowKind::Port { origin, .. } if origin == "devel/shared"))
        .expect("dependency should still be listed");
    assert!(!graph.visible_rows[shared_row].is_expanded);

    graph.expand_node(root_row);
    assert!(graph.visible_rows[root_row].is_expanded);
    assert_eq!(graph.visible_rows.len(), before);

    // Opening the option reveals its dependency reference, but the dependency's
    // own entry elsewhere in the list is untouched
    graph.expand_node(root_row + 1);
    assert!(graph
        .visible_rows
        .iter()
        .any(|r| matches!(&r.kind, RowKind::DependsOn { origin, .. } if origin == "devel/shared")));
    let shared_row = graph
        .visible_rows
        .iter()
        .position(|r| matches!(&r.kind, RowKind::Port { origin, .. } if origin == "devel/shared"))
        .expect("dependency should still be listed");
    assert!(!graph.visible_rows[shared_row].is_expanded);
}

#[test]
fn test_recenter_positions_cursor_middle_top_and_bottom() {
    // 40-row list, cursor on row 20, 10 visible rows
    assert_eq!(
        recenter_offset(20, 10, 40, RecenterPosition::Middle),
        15,
        "middle should leave half a screen above the cursor"
    );
    assert_eq!(recenter_offset(20, 10, 40, RecenterPosition::Top), 20);
    assert_eq!(recenter_offset(20, 10, 40, RecenterPosition::Bottom), 11);
}

#[test]
fn test_recenter_cycle_follows_emacs_order() {
    // Emacs recenter-top-bottom: middle -> top -> bottom -> middle
    let mut pos = RecenterPosition::Middle;
    pos = pos.next();
    assert_eq!(pos, RecenterPosition::Top);
    pos = pos.next();
    assert_eq!(pos, RecenterPosition::Bottom);
    pos = pos.next();
    assert_eq!(pos, RecenterPosition::Middle);
}

#[test]
fn test_recenter_clamps_near_the_edges_of_the_list() {
    // Cannot scroll above the first row
    for pos in [
        RecenterPosition::Middle,
        RecenterPosition::Top,
        RecenterPosition::Bottom,
    ] {
        assert_eq!(recenter_offset(0, 10, 40, pos), 0);
    }
    assert_eq!(recenter_offset(2, 10, 40, RecenterPosition::Middle), 0);

    // Near the end, the offset never runs past the final row
    assert_eq!(recenter_offset(39, 10, 40, RecenterPosition::Top), 39);
    assert_eq!(recenter_offset(39, 10, 40, RecenterPosition::Bottom), 30);

    // Degenerate viewports do not panic
    assert_eq!(recenter_offset(5, 0, 40, RecenterPosition::Middle), 5);
    assert_eq!(recenter_offset(5, 1, 40, RecenterPosition::Bottom), 5);
    assert_eq!(recenter_offset(5, 1, 40, RecenterPosition::Middle), 5);
}

#[test]
fn test_ignore_missing_flag_still_bails_if_zero_total_ports_match() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["invalid/port1".to_string(), "invalid/port2".to_string()];

    // With ignore_missing = true, if 0 total ports match, it MUST still bail out
    let result = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, true);
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found for pattern(s)"));
}

// ============================================================================
// 10. GROUPS (option choices kept in step across a family of ports)
// ============================================================================

/// A database where three ports share an option name, one of them also has a
/// radio group, and one lacks the shared option entirely.
fn group_db() -> Connection {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    for origin in [
        "lang/php83-extensions",
        "lang/php84-extensions",
        "lang/php85-extensions",
        "www/unrelated",
    ] {
        let name = origin.split('/').nth(1).unwrap();
        conn.execute(
            "INSERT INTO ports (origin, name, version, comment) VALUES (?1, ?2, '1.0', '')",
            rusqlite::params![origin, name],
        )
        .unwrap();
    }

    let add = |origin: &str, opt: &str, default: i32, gt: &str, gn: &str| {
        conn.execute(
            "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
             VALUES (?1, ?2, ?3, '', ?4, ?5)",
            rusqlite::params![origin, opt, default, gt, gn],
        )
        .unwrap();
    };

    for origin in [
        "lang/php83-extensions",
        "lang/php84-extensions",
        "lang/php85-extensions",
    ] {
        add(origin, "SOAP", 0, "DEFINE", "");
    }
    // Only php83 has this one, so the others must be left alone
    add("lang/php83-extensions", "ONLY_ON_83", 0, "DEFINE", "");

    // A radio group php83 and php84 both have, but php84 has an extra member
    for origin in ["lang/php83-extensions", "lang/php84-extensions"] {
        add(origin, "MYSQL", 1, "SINGLE", "DB");
        add(origin, "PGSQL", 0, "SINGLE", "DB");
    }
    add("lang/php84-extensions", "SQLITE", 0, "SINGLE", "DB");

    add("www/unrelated", "SOAP", 0, "DEFINE", "");
    conn
}

fn load_grouped(conn: &Connection, groups: &[(&str, &[&str])]) -> DependencyGraph {
    let targets: Vec<String> = vec![
        "lang/php83-extensions".to_string(),
        "lang/php84-extensions".to_string(),
        "lang/php85-extensions".to_string(),
        "www/unrelated".to_string(),
    ];
    let mut graph =
        DependencyGraph::load_from_db(conn, &targets, &SystemOptions::default(), false).unwrap();
    for (name, members) in groups {
        graph.groups.insert(
            name.to_string(),
            members.iter().map(|m| m.to_string()).collect(),
        );
    }
    graph.expand_all();
    graph
}

fn enabled_of(graph: &DependencyGraph, origin: &str, opt: &str) -> Option<bool> {
    graph
        .option_nodes
        .iter()
        .find(|o| o.port_origin == origin && o.name == opt)
        .map(|o| o.enabled)
}

/// The whole point: setting an option on one member sets it on the rest.
#[test]
fn test_toggling_a_member_sets_the_option_across_the_group() {
    let conn = group_db();
    let mut graph = load_grouped(
        &conn,
        &[(
            "php-extensions",
            &[
                "lang/php83-extensions",
                "lang/php84-extensions",
                "lang/php85-extensions",
            ],
        )],
    );

    for origin in [
        "lang/php83-extensions",
        "lang/php84-extensions",
        "lang/php85-extensions",
    ] {
        assert_eq!(enabled_of(&graph, origin, "SOAP"), Some(false));
    }

    let row = find_option_row(&graph, "lang/php83-extensions", "SOAP");
    graph.toggle_option(row);

    for origin in [
        "lang/php83-extensions",
        "lang/php84-extensions",
        "lang/php85-extensions",
    ] {
        assert_eq!(
            enabled_of(&graph, origin, "SOAP"),
            Some(true),
            "{origin} did not follow"
        );
    }

    // A port outside the group is untouched
    assert_eq!(enabled_of(&graph, "www/unrelated", "SOAP"), Some(false));

    // ...and turning it back off propagates too
    let row = find_option_row(&graph, "lang/php84-extensions", "SOAP");
    graph.toggle_option(row);
    for origin in [
        "lang/php83-extensions",
        "lang/php84-extensions",
        "lang/php85-extensions",
    ] {
        assert_eq!(enabled_of(&graph, origin, "SOAP"), Some(false));
    }
}

/// Members do not have identical option sets, and an option only one of them
/// defines must not be invented on the others.
#[test]
fn test_an_option_only_one_member_has_stays_there() {
    let conn = group_db();
    let mut graph = load_grouped(
        &conn,
        &[(
            "php-extensions",
            &["lang/php83-extensions", "lang/php84-extensions"],
        )],
    );

    let row = find_option_row(&graph, "lang/php83-extensions", "ONLY_ON_83");
    graph.toggle_option(row);

    assert_eq!(
        enabled_of(&graph, "lang/php83-extensions", "ONLY_ON_83"),
        Some(true)
    );
    assert_eq!(
        enabled_of(&graph, "lang/php84-extensions", "ONLY_ON_83"),
        None,
        "the option must not be conjured onto a member that lacks it"
    );
}

/// A radio pick has to resolve against each member's own siblings, which are not
/// necessarily the same set as the port the choice was made on.
#[test]
fn test_a_radio_pick_resolves_against_each_members_own_siblings() {
    let conn = group_db();
    let mut graph = load_grouped(
        &conn,
        &[(
            "php-extensions",
            &["lang/php83-extensions", "lang/php84-extensions"],
        )],
    );

    // MYSQL is the default on both; php84 additionally offers SQLITE
    assert_eq!(
        enabled_of(&graph, "lang/php84-extensions", "MYSQL"),
        Some(true)
    );
    assert_eq!(
        enabled_of(&graph, "lang/php84-extensions", "SQLITE"),
        Some(false)
    );

    let row = find_option_row(&graph, "lang/php83-extensions", "PGSQL");
    graph.toggle_option(row);

    for origin in ["lang/php83-extensions", "lang/php84-extensions"] {
        assert_eq!(enabled_of(&graph, origin, "PGSQL"), Some(true), "{origin}");
        assert_eq!(
            enabled_of(&graph, origin, "MYSQL"),
            Some(false),
            "{origin} kept two radio members on"
        );
    }
    assert_eq!(
        enabled_of(&graph, "lang/php84-extensions", "SQLITE"),
        Some(false),
        "php84's extra radio member must be off as well"
    );
}

/// Pressing Space on a radio that is already selected does nothing, in a group
/// exactly as outside one.
#[test]
fn test_reselecting_a_radio_changes_nothing() {
    let conn = group_db();
    let mut graph = load_grouped(
        &conn,
        &[(
            "php-extensions",
            &["lang/php83-extensions", "lang/php84-extensions"],
        )],
    );

    let row = find_option_row(&graph, "lang/php83-extensions", "MYSQL");
    graph.toggle_option(row);

    for origin in ["lang/php83-extensions", "lang/php84-extensions"] {
        assert_eq!(enabled_of(&graph, origin, "MYSQL"), Some(true));
        assert_eq!(enabled_of(&graph, origin, "PGSQL"), Some(false));
    }
    assert!(!graph.is_dirty(), "nothing actually changed");
}

/// A port can belong to more than one group, and a choice reaches the union.
#[test]
fn test_a_port_in_two_groups_reaches_both() {
    let conn = group_db();
    let mut graph = load_grouped(
        &conn,
        &[
            ("a", &["lang/php83-extensions", "lang/php84-extensions"]),
            ("b", &["lang/php83-extensions", "lang/php85-extensions"]),
        ],
    );

    let row = find_option_row(&graph, "lang/php83-extensions", "SOAP");
    graph.toggle_option(row);

    for origin in [
        "lang/php83-extensions",
        "lang/php84-extensions",
        "lang/php85-extensions",
    ] {
        assert_eq!(enabled_of(&graph, origin, "SOAP"), Some(true), "{origin}");
    }
}

/// A group naming a port that is not in the current list is not an error; the
/// membership simply waits for it.
#[test]
fn test_a_member_outside_the_current_list_is_skipped() {
    let conn = group_db();
    let mut graph = load_grouped(
        &conn,
        &[(
            "php-extensions",
            &[
                "lang/php83-extensions",
                "lang/php84-extensions",
                "lang/php99-nonexistent",
            ],
        )],
    );

    let row = find_option_row(&graph, "lang/php83-extensions", "SOAP");
    graph.toggle_option(row);

    assert_eq!(
        enabled_of(&graph, "lang/php84-extensions", "SOAP"),
        Some(true)
    );
    assert!(graph.port_index("lang/php99-nonexistent").is_none());
    // ...and the group still names it, ready for a run that includes it
    assert!(graph.groups["php-extensions"].contains(&"lang/php99-nonexistent".to_string()));
}

/// With no groups configured, toggling behaves exactly as it did before groups
/// existed.
#[test]
fn test_without_groups_a_toggle_touches_only_its_own_port() {
    let conn = group_db();
    let mut graph = load_grouped(&conn, &[]);

    let row = find_option_row(&graph, "lang/php83-extensions", "SOAP");
    graph.toggle_option(row);

    assert_eq!(
        enabled_of(&graph, "lang/php83-extensions", "SOAP"),
        Some(true)
    );
    for origin in ["lang/php84-extensions", "lang/php85-extensions"] {
        assert_eq!(enabled_of(&graph, origin, "SOAP"), Some(false), "{origin}");
    }
}

// ============================================================================
// 11. SEARCH (narrows which ports are listed, on their origin)
// ============================================================================

/// Three ports where the word "postgres" appears in a *different* place for
/// each: one origin, one option description, one option name.
fn search_db() -> Connection {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    for (origin, opt, desc) in [
        ("databases/postgresql16-server", "SSL", "Secure sockets"),
        ("devel/git", "DOCS", "Postgres support"),
        ("www/nginx", "POSTGRES", "Database backend"),
    ] {
        conn.execute(
            "INSERT INTO ports (origin, name, version, comment) VALUES (?1, ?2, '1.0', '')",
            rusqlite::params![origin, origin.split('/').nth(1).unwrap()],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
             VALUES (?1, ?2, 1, ?3, 'DEFINE', '')",
            rusqlite::params![origin, opt, desc],
        )
        .unwrap();
    }
    conn.execute(
        "INSERT INTO port_deps (port_origin, dep_origin, dep_type)
         VALUES ('www/nginx', 'databases/postgresql16-server', 'LIB')",
        [],
    )
    .unwrap();
    conn
}

fn searched(graph: &mut DependencyGraph, query: &str) -> Vec<String> {
    graph.search_query = query.to_string();
    graph.rebuild_visible_rows();
    listed_origins(graph)
}

fn search_graph() -> DependencyGraph {
    let conn = search_db();
    let targets: Vec<String> = ["databases/postgresql16-server", "devel/git", "www/nginx"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &targets, &SystemOptions::default(), false).unwrap();
    graph.expand_all();
    graph
}

/// Search matches the port origin and nothing else. An option whose name or
/// description happens to contain the word does not drag its port in.
#[test]
fn search_matches_port_origins_only() {
    let mut graph = search_graph();

    assert_eq!(
        searched(&mut graph, "postgres"),
        vec!["databases/postgresql16-server"],
        "devel/git matched only in a description and www/nginx only in an option name"
    );

    // The category half of the origin works too
    assert_eq!(
        searched(&mut graph, "databases/"),
        vec!["databases/postgresql16-server"]
    );
    // ...as does a fragment of the name half
    assert_eq!(searched(&mut graph, "ngin"), vec!["www/nginx"]);
}

/// A port that matches is shown whole. Filtering row by row used to sever
/// options from their port and leave section headers with nothing under them.
#[test]
fn a_matching_port_keeps_all_of_its_rows() {
    let mut graph = search_graph();
    searched(&mut graph, "postgres");

    // header, its option, the required-by header, and the entry under it
    let kinds: Vec<&str> = graph
        .visible_rows
        .iter()
        .map(|r| match &r.kind {
            RowKind::Port { .. } => "port",
            RowKind::Option { .. } => "option",
            RowKind::SectionHeader { .. } => "section",
            RowKind::RequiredByEntry { .. } => "required-by",
            RowKind::RequiresEntry { .. } => "requires",
            RowKind::DependsOn { .. } => "depends-on",
            RowKind::Info { .. } => "info",
        })
        .collect();

    assert_eq!(kinds, vec!["port", "option", "section", "required-by"]);
}

/// Every row shown has to belong to a port that is shown. An orphaned option or
/// a section header with no port above it is what made this confusing.
#[test]
fn no_row_is_left_without_its_port() {
    let mut graph = search_graph();

    for query in ["postgres", "git", "www", "zzz-matches-nothing", ""] {
        searched(&mut graph, query);

        let mut seen_a_port = false;
        for row in &graph.visible_rows {
            match &row.kind {
                RowKind::Port { .. } => seen_a_port = true,
                other => assert!(
                    seen_a_port,
                    "query {query:?} left {other:?} with no port above it"
                ),
            }
        }
    }
}

#[test]
fn search_is_case_insensitive_and_can_match_nothing() {
    let mut graph = search_graph();

    assert_eq!(
        searched(&mut graph, "POSTGRESQL16"),
        vec!["databases/postgresql16-server"]
    );
    assert!(searched(&mut graph, "no-such-port").is_empty());

    // ...and clearing it brings everything back
    assert_eq!(searched(&mut graph, "").len(), 3);
}

/// The count in the header comes from this, and has to follow the filter.
#[test]
fn the_listed_port_count_follows_the_filter() {
    let mut graph = search_graph();

    assert_eq!(graph.listed_port_count(), 3);
    assert_eq!(
        graph.live_count(),
        3,
        "filtering does not change reachability"
    );

    searched(&mut graph, "postgres");
    assert_eq!(graph.listed_port_count(), 1);
    assert_eq!(
        graph.live_count(),
        3,
        "a search hides ports; it does not remove them from the build"
    );
}

/// A filtered-out port keeps its options, so they are still written on save.
/// Search is a view, not a selection.
#[test]
fn filtering_does_not_change_what_gets_written() {
    let temp = TempDir::new("search_export");
    let options_dir = temp.path.join("ports");

    let mut graph = search_graph();
    searched(&mut graph, "postgres");
    assert_eq!(graph.listed_port_count(), 1);

    exporter::export_options(&graph, &options_dir, false, None).unwrap();

    for port in ["databases_postgresql16-server", "devel_git", "www_nginx"] {
        assert!(
            options_dir.join(port).join("options").exists(),
            "{port} was hidden by the filter but must still be written"
        );
    }
}
