use rusqlite::Connection;
use std::fs;
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};

use bgone::db;
use bgone::exporter;
use bgone::graph::{DependencyGraph, RowKind};
use bgone::indexer;
use bgone::reader::SystemOptions;

static TEMP_COUNTER: AtomicUsize = AtomicUsize::new(0);

/// RAII wrapper to guarantee test directories and files are cleaned up on completion or panic.
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new(prefix: &str) -> Self {
        let count = TEMP_COUNTER.fetch_add(1, Ordering::SeqCst);
        let mut path = std::env::temp_dir();
        path.push(format!(
            "bgone_test_{}_{}_{}",
            prefix,
            std::process::id(),
            count
        ));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("Failed to create temporary test directory");
        Self { path }
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

// ============================================================================
// 1. READER TESTS (Existing Options & make.conf)
// ============================================================================

#[test]
fn test_reader_precedence_and_parsing() {
    let temp = TempDir::new("reader");

    // Setup mock /var/db/ports/www_apache24/options
    let ports_dir = temp.path.join("ports");
    let apache_opts_dir = ports_dir.join("www_apache24");
    fs::create_dir_all(&apache_opts_dir).unwrap();
    fs::write(
        apache_opts_dir.join("options"),
        "# Mock options\n_OPTIONS_READ=apache24\nWITH_HTTP2=true\nWITHOUT_DOCS=true\n",
    )
    .unwrap();

    // Setup mock make.conf
    let make_conf = temp.path.join("make.conf");
    fs::write(
        &make_conf,
        "# Global options\nOPTIONS_SET+=GLOBAL_SET\nOPTIONS_UNSET+=GLOBAL_UNSET\n",
    )
    .unwrap();

    let sys_opts = SystemOptions::load(&ports_dir, Some(&make_conf));

    // 1. Per-port overrides
    assert_eq!(sys_opts.get_state("www/apache24", "HTTP2", false), true);
    assert_eq!(sys_opts.get_state("www/apache24", "DOCS", true), false);

    // 2. Global make.conf overrides
    assert_eq!(sys_opts.get_state("dns/bind9", "GLOBAL_SET", false), true);
    assert_eq!(sys_opts.get_state("dns/bind9", "GLOBAL_UNSET", true), false);

    // 3. Fallback to Makefile defaults when no override exists
    assert_eq!(
        sys_opts.get_state("www/apache24", "UNTOUCHED_OPT", true),
        true
    );
    assert_eq!(
        sys_opts.get_state("www/apache24", "UNTOUCHED_OPT", false),
        false
    );
}

// ============================================================================
// 2. EXPORTER TESTS (Output File Validation & Dry-Run)
// ============================================================================

#[test]
fn test_exporter_writes_valid_options_files() {
    let temp = TempDir::new("exporter_write");
    let options_dir = temp.path.join("ports");
    let make_conf_path = temp.path.join("make.conf");

    // Set up database and graph
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('www/apache24', 'HTTP2', 1, 'Enable HTTP2', 'DEFINE', ''),
                ('www/apache24', 'DOCS', 0, 'Build Docs', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["www/apache24".to_string()], &sys_opts, false)
            .unwrap();

    // Export options
    let stats =
        exporter::export_options(&graph, &options_dir, false, Some(&make_conf_path)).unwrap();

    assert_eq!(stats.files_written, 1);
    assert_eq!(stats.options_saved, 2);

    // Validate generated /var/db/ports/www_apache24/options file content
    let exported_file = options_dir.join("www_apache24").join("options");
    assert!(exported_file.exists());

    let content = fs::read_to_string(&exported_file).unwrap();
    assert!(content.contains("# Generated by bgone"));
    assert!(content.contains("_OPTIONS_READ=apache24"));
    assert!(content.contains("WITH_HTTP2=true"));
    assert!(content.contains("WITHOUT_DOCS=true"));

    // Validate generated make.conf file content
    assert!(make_conf_path.exists());
    let make_content = fs::read_to_string(&make_conf_path).unwrap();
    assert!(make_content.contains("OPTIONS_SET+=HTTP2"));
    assert!(make_content.contains("OPTIONS_UNSET+=DOCS"));
}

#[test]
fn test_exporter_dry_run_creates_no_files() {
    let temp = TempDir::new("exporter_dryrun");
    let options_dir = temp.path.join("ports");

    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('sysutils/tmux', 'tmux', '3.3', 'Terminal Multiplexer')",
        [],
    ).unwrap();
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('sysutils/tmux', 'UTF8BIDI', 1, 'Support UTF8 BIDI', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let graph =
        DependencyGraph::load_from_db(&conn, &["sysutils/tmux".to_string()], &sys_opts, false)
            .unwrap();

    // Run export in dry-run mode
    let stats =
        exporter::export_options(&graph, &options_dir, true, None::<&std::path::PathBuf>).unwrap();

    assert_eq!(stats.files_written, 1);
    assert!(
        !options_dir.exists(),
        "Dry run must NOT create files on disk!"
    );
}

// ============================================================================
// 3. INDEXER & DB TESTS (Parallel Processing & Parser)
// ============================================================================

#[test]
fn test_indexer_parses_ports_dir_into_sqlite() {
    let temp = TempDir::new("indexer");
    let ports_root = temp.path.join("ports");

    // Construct mock ports directory tree
    let nginx_dir = ports_root.join("www").join("nginx");
    fs::create_dir_all(&nginx_dir).unwrap();

    let makefile_content = r#"
PORTNAME=   nginx
PORTVERSION=1.24.0
COMMENT=    Robust HTTP and reverse proxy server

OPTIONS_DEFINE=   HTTP2 SSL DEBUG
OPTIONS_SINGLE=   GZIP
OPTIONS_SINGLE_GZIP= GZIP_DEF GZIP_ALT
OPTIONS_DEFAULT=  HTTP2 GZIP_DEF

HTTP2_DESC=       Enable HTTP2 protocol support
SSL_DESC=         Enable SSL protocol support

HTTP2_RUN_DEPENDS= www/nghttp2
"#;
    fs::write(nginx_dir.join("Makefile"), makefile_content).unwrap();

    let mut conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let stats = indexer::index_ports_dir(&mut conn, &ports_root).unwrap();

    assert_eq!(stats.ports_indexed, 1);
    assert_eq!(stats.options_indexed, 5); // HTTP2, SSL, DEBUG, GZIP_DEF, GZIP_ALT
    assert_eq!(stats.option_deps_indexed, 1); // HTTP2 -> www/nghttp2

    // Query SQLite database directly to verify values
    let count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM ports WHERE origin = 'www/nginx'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(count, 1);

    let http2_default: i32 = conn
        .query_row(
            "SELECT default_state FROM options WHERE port_origin = 'www/nginx' AND option_name = 'HTTP2'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(http2_default, 1);

    let debug_default: i32 = conn
        .query_row(
            "SELECT default_state FROM options WHERE port_origin = 'www/nginx' AND option_name = 'DEBUG'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(debug_default, 0);
}

// ============================================================================
// 4. GRAPH ENGINE TESTS (Radio Buttons, Search, Expansion)
// ============================================================================

#[test]
fn test_graph_radio_group_mutual_exclusion() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('databases/db', 'db', '1.0', 'Database')",
        [],
    ).unwrap();

    // Insert two options in the same SINGLE group
    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('databases/db', 'ENGINE_A', 1, 'Engine A', 'SINGLE', 'ENGINE'),
                ('databases/db', 'ENGINE_B', 0, 'Engine B', 'SINGLE', 'ENGINE')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["databases/db".to_string()], &sys_opts, false)
            .unwrap();

    // Verify initial states
    assert!(graph.option_nodes[0].enabled); // ENGINE_A
    assert!(!graph.option_nodes[1].enabled); // ENGINE_B

    // Row 0 is the root Port (already expanded by default).
    // Row 1 is ENGINE_A, Row 2 is ENGINE_B.
    // Toggle ENGINE_B at row 2 directly:
    graph.toggle_option(2);

    // Verify mutual exclusion: ENGINE_B becomes enabled, ENGINE_A becomes disabled
    assert!(!graph.option_nodes[0].enabled); // ENGINE_A disabled
    assert!(graph.option_nodes[1].enabled); // ENGINE_B enabled
}

#[test]
fn test_graph_search_filtering() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('net/curl', 'curl', '8.0', 'Data transfer tool')",
        [],
    ).unwrap();

    conn.execute(
        "INSERT INTO options (port_origin, option_name, default_state, description, group_type, group_name)
         VALUES ('net/curl', 'HTTP2', 1, 'Enable HTTP2 support', 'DEFINE', ''),
                ('net/curl', 'OPENSSL', 1, 'Use OpenSSL backend', 'DEFINE', ''),
                ('net/curl', 'COOKIES', 0, 'Enable Cookie support', 'DEFINE', '')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let mut graph =
        DependencyGraph::load_from_db(&conn, &["net/curl".to_string()], &sys_opts, false).unwrap();

    // Expand all nodes
    graph.expand_all();
    let total_unfiltered_rows = graph.visible_rows.len();

    // Filter for "SSL"
    graph.search_query = "SSL".to_string();
    graph.rebuild_visible_rows();

    assert!(graph.visible_rows.len() < total_unfiltered_rows);
    assert!(graph.visible_rows.iter().any(|r| match &r.kind {
        RowKind::Option { name, .. } => name == "OPENSSL",
        _ => false,
    }));

    // Clear search filter
    graph.search_query.clear();
    graph.rebuild_visible_rows();
    assert_eq!(graph.visible_rows.len(), total_unfiltered_rows);
}

#[test]
fn test_unknown_port_returns_error() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let sys_opts = SystemOptions::default();
    let result =
        DependencyGraph::load_from_db(&conn, &["nonexistent/port".to_string()], &sys_opts, false);

    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found"));
}

#[test]
fn test_graph_glob_pattern_resolution() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES
         ('www/py-django', 'py-django', '4.2', 'Web Framework'),
         ('www/py-requests', 'py-requests', '2.31', 'HTTP Library')",
        [],
    )
    .unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/py-*".to_string()];
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false).unwrap();

    assert_eq!(graph.root_port_ids.len(), 2);
    assert!(graph.root_origin.contains("2 ports matched"));
}

#[test]
fn test_pattern_matching_zero_ports_returns_error() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["nonexistent/*".to_string()];

    let result = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false);

    // Bails when zero ports match across all provided patterns
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found for pattern(s): 'nonexistent/*'"));
}

#[test]
fn test_mixed_delimiter_ports_file_parsing() {
    let temp = TempDir::new("file_parsing");
    let ports_file = temp.path.join("my_ports.txt");

    // File containing mixed commas, tabs, spaces, newlines, full comments, and inline comments
    let file_content = r#"
# Core infrastructure
www/apache24, databases/postgresql16-server  lang/python311 # inline comment

# Wildcards
www/py-*, net/curl
"#;
    fs::write(&ports_file, file_content).unwrap();

    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES
         ('www/apache24', 'apache', '2.4', 'Server'),
         ('databases/postgresql16-server', 'pg', '16.0', 'DB'),
         ('lang/python311', 'python', '3.11', 'Lang'),
         ('www/py-django', 'django', '4.2', 'Web'),
         ('net/curl', 'curl', '8.0', 'Tool')",
        [],
    )
    .unwrap();

    let content = fs::read_to_string(&ports_file).unwrap();
    let targets: Vec<String> = content
        .lines()
        .map(|line| line.split('#').next().unwrap_or(""))
        .flat_map(|line| line.split(|c: char| c == ',' || c.is_whitespace()))
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .map(String::from)
        .collect();

    let sys_opts = SystemOptions::default();
    let graph = DependencyGraph::load_from_db(&conn, &targets, &sys_opts, false).unwrap();

    // Should resolve all 5 matching ports cleanly
    assert_eq!(graph.root_port_ids.len(), 5);
}

#[test]
fn test_multiple_ports_with_one_unknown_returns_error() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/apache24".to_string(), "invalid/unknown".to_string()];

    let result = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, false);

    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found for pattern(s): 'invalid/unknown'"));
}

#[test]
fn test_ignore_missing_flag_warns_and_continues() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    conn.execute(
        "INSERT INTO ports (origin, name, version, comment) VALUES ('www/apache24', 'apache', '2.4.58', 'Web Server')",
        [],
    ).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["www/apache24".to_string(), "invalid/unknown".to_string()];

    // With ignore_missing = true, valid port loads cleanly and doesn't bail out
    let graph = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, true).unwrap();
    assert_eq!(graph.root_port_ids.len(), 1);
}

#[test]
fn test_ignore_missing_flag_still_bails_if_zero_total_ports_match() {
    let conn = Connection::open_in_memory().unwrap();
    db::init_db(&conn, true).unwrap();

    let sys_opts = SystemOptions::default();
    let patterns = vec!["invalid/port1".to_string(), "invalid/port2".to_string()];

    // With ignore_missing = true, if 0 total ports match, it MUST still bail out
    let result = DependencyGraph::load_from_db(&conn, &patterns, &sys_opts, true);
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("No matching ports found for pattern(s)"));
}
