use crate::graph::DependencyGraph;
use anyhow::{Context, Result};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

pub struct ExporterStats {
    pub files_written: usize,
    pub options_saved: usize,
}

pub fn export_options(
    graph: &DependencyGraph,
    options_dir: &Path,
    dry_run: bool,
    make_conf_path: Option<&PathBuf>,
) -> Result<ExporterStats> {
    let mut stats = ExporterStats {
        files_written: 0,
        options_saved: 0,
    };

    // Group options by port origin (e.g., "www/apache24" -> "www_apache24").
    //
    // Only ports something currently pulls in are written. A port stranded by
    // an option being turned off is not part of the build, so writing an options
    // file for it would leave stale configuration behind for a port that is not
    // there — its selections stay in memory instead, ready if it comes back.
    let mut port_options: HashMap<String, Vec<(String, bool)>> = HashMap::new();

    for opt in graph
        .real_options()
        .filter(|opt| graph.is_live(&opt.port_origin))
    {
        port_options
            .entry(opt.port_origin.clone())
            .or_default()
            .push((opt.name.clone(), opt.enabled));
    }

    // Sorted so repeated runs write files in a stable order
    let mut origins: Vec<String> = port_options.keys().cloned().collect();
    origins.sort();

    for origin in origins {
        let parts: Vec<&str> = origin.split('/').collect();
        if parts.len() != 2 {
            continue;
        }

        let dir_name = format!("{}_{}", parts[0], parts[1]);
        let target_dir = options_dir.join(&dir_name);
        let target_file = target_dir.join("options");

        // Sorted so repeated runs produce byte-identical files
        let mut opts = port_options[&origin].clone();
        opts.sort_by(|a, b| a.0.cmp(&b.0));

        let pkg_name = graph
            .pkg_names
            .get(&origin)
            .cloned()
            .unwrap_or_else(|| parts[1].to_string());
        let complete_list: Vec<&str> = opts.iter().map(|(name, _)| name.as_str()).collect();

        // Mirrors the file `make config` writes (bsd.port.mk, do-config). Only
        // OPTIONS_FILE_SET / OPTIONS_FILE_UNSET are actually consumed, by
        // bsd.options.mk; the two underscore-prefixed headers are informational,
        // but `make showconfig` and human readers expect them.
        //
        // Every option the port defines must appear in one list or the other:
        // bsd.port.mk's `config-conditional` re-opens the dialog whenever
        // NEW_OPTIONS (COMPLETE_OPTIONS_LIST minus everything named here) is
        // non-empty, so an option omitted because the user never touched it is
        // enough to make poudriere prompt for the whole port again.
        let mut content = String::new();
        content.push_str("# This file is auto-generated by bgone.\n");
        content.push_str(&format!("# Options for {}\n", pkg_name));
        content.push_str(&format!("_OPTIONS_READ={}\n", pkg_name));
        content.push_str(&format!(
            "_FILE_COMPLETE_OPTIONS_LIST={}\n",
            complete_list.join(" ")
        ));

        for (opt_name, enabled) in &opts {
            if *enabled {
                content.push_str(&format!("OPTIONS_FILE_SET+={}\n", opt_name));
            } else {
                content.push_str(&format!("OPTIONS_FILE_UNSET+={}\n", opt_name));
            }
            stats.options_saved += 1;
        }

        if dry_run {
            println!("\n[DRY RUN] Would write to {:?}:\n---", target_file);
            print!("{}", content);
            println!("---");
            stats.files_written += 1;
        } else {
            fs::create_dir_all(&target_dir).with_context(|| {
                format!("Failed to create options directory at {:?}", target_dir)
            })?;
            fs::write(&target_file, &content)
                .with_context(|| format!("Failed to write options file at {:?}", target_file))?;
            stats.files_written += 1;
        }
    }

    // Optional: Export global make.conf snippet if configured
    if let Some(m_path) = make_conf_path {
        let mut make_content = String::new();
        make_content.push_str("# Generated by bgone - Global Overrides\n");

        let mut seen_globals: HashSet<(&str, bool)> = HashSet::new();
        for opt in graph.real_options() {
            if !seen_globals.insert((opt.name.as_str(), opt.enabled)) {
                continue;
            }
            let key = if opt.enabled {
                "OPTIONS_SET"
            } else {
                "OPTIONS_UNSET"
            };
            make_content.push_str(&format!("{}+={}\n", key, opt.name));
        }

        if dry_run {
            println!("\n[DRY RUN] Would write make.conf to {:?}:\n---", m_path);
            print!("{}", make_content);
            println!("---");
        } else {
            if let Some(parent) = m_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(m_path, make_content)?;
            println!("[+] Global options written to {:?}", m_path);
        }
    }

    Ok(stats)
}
