use crate::graph::DependencyGraph;
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

pub struct ExporterStats {
    pub files_written: usize,
    pub options_saved: usize,
}

pub fn export_options(
    graph: &DependencyGraph,
    options_dir: &Path,
    dry_run: bool,
    make_conf_path: Option<&PathBuf>,
) -> Result<ExporterStats> {
    let mut stats = ExporterStats {
        files_written: 0,
        options_saved: 0,
    };

    // Group options by port origin (e.g., "www/apache24" -> "www_apache24")
    let mut port_options: HashMap<String, Vec<(String, bool)>> = HashMap::new();

    for opt in &graph.option_nodes {
        port_options
            .entry(opt.port_origin.clone())
            .or_default()
            .push((opt.name.clone(), opt.enabled));
    }

    for (origin, opts) in port_options {
        let parts: Vec<&str> = origin.split('/').collect();
        if parts.len() != 2 {
            continue;
        }

        let dir_name = format!("{}_{}", parts[0], parts[1]);
        let target_dir = options_dir.join(&dir_name);
        let target_file = target_dir.join("options");

        let mut content = String::new();
        content.push_str("# Generated by bgone\n");
        content.push_str(&format!("_OPTIONS_READ={}\n", parts[1]));

        for (opt_name, enabled) in &opts {
            if *enabled {
                content.push_str(&format!("WITH_{}=true\n", opt_name));
            } else {
                content.push_str(&format!("WITHOUT_{}=true\n", opt_name));
            }
            stats.options_saved += 1;
        }

        if dry_run {
            println!("\n[DRY RUN] Would write to {:?}:\n---", target_file);
            print!("{}", content);
            println!("---");
            stats.files_written += 1;
        } else {
            fs::create_dir_all(&target_dir).with_context(|| {
                format!("Failed to create options directory at {:?}", target_dir)
            })?;
            fs::write(&target_file, &content)
                .with_context(|| format!("Failed to write options file at {:?}", target_file))?;
            stats.files_written += 1;
        }
    }

    // Optional: Export global make.conf snippet if configured
    if let Some(m_path) = make_conf_path {
        let mut make_content = String::new();
        make_content.push_str("# Generated by bgone - Global Overrides\n");

        for opt in &graph.option_nodes {
            let key = if opt.enabled {
                "OPTIONS_SET"
            } else {
                "OPTIONS_UNSET"
            };
            make_content.push_str(&format!("{}+={}\n", key, opt.name));
        }

        if dry_run {
            println!("\n[DRY RUN] Would write make.conf to {:?}:\n---", m_path);
            print!("{}", make_content);
            println!("---");
        } else {
            if let Some(parent) = m_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(m_path, make_content)?;
            println!("[+] Global options written to {:?}", m_path);
        }
    }

    Ok(stats)
}
